language: node_js
node_js:
      - "9"
      - "12"
      - "16"
before_install: npm install && npm run build
script: 
    - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" -e "s#@SERVICE_URL@#https://www.kaltura.com#g" src/tests/tests-config.template.ts > src/tests/tests-config.ts
    - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" -e "s#@SERVICE_URL@#https://www.kaltura.com#g" -i src/tests/kaltura-request.spec.ts 
    - npm run test
notifications:
  email:
    recipients:
      - jess.portnoy@kaltura.com
      - eran.sakal@kaltura.com
      - amir.chervinsky@kaltura.com
    on_success: change
    on_failure: always
