

import { KalturaObjectBase } from '../kaltura-object-base';
import { KalturaTypesFactory } from '../kaltura-types-factory';

export class KalturaLanguage extends KalturaObjectBase {
    private _value : string;
    constructor( value?:string | number){
        super();
        this._value = value + '';
    }

    equals(obj : this) : boolean
    {
        return obj && obj.toString() === this._value;
    }

    toString(){
        return this._value;
    }

    static aa = new KalturaLanguage('Afar');
	static ab = new KalturaLanguage('Abkhazian');
	static af = new KalturaLanguage('Afrikaans');
	static am = new KalturaLanguage('Amharic');
	static ar = new KalturaLanguage('Arabic');
	static as = new KalturaLanguage('Assamese');
	static ay = new KalturaLanguage('Aymara');
	static az = new KalturaLanguage('Azerbaijani');
	static ba = new KalturaLanguage('Bashkir');
	static be = new KalturaLanguage('Byelorussian (Belarusian)');
	static bg = new KalturaLanguage('Bulgarian');
	static bh = new KalturaLanguage('Bihari');
	static bi = new KalturaLanguage('Bislama');
	static bn = new KalturaLanguage('Bengali (Bangla)');
	static bo = new KalturaLanguage('Tibetan');
	static br = new KalturaLanguage('Breton');
	static ca = new KalturaLanguage('Catalan');
	static co = new KalturaLanguage('Corsican');
	static cs = new KalturaLanguage('Czech');
	static cy = new KalturaLanguage('Welsh');
	static da = new KalturaLanguage('Danish');
	static de = new KalturaLanguage('German');
	static dz = new KalturaLanguage('Bhutani');
	static el = new KalturaLanguage('Greek');
	static en = new KalturaLanguage('English');
	static enGb = new KalturaLanguage('English (British)');
	static enUs = new KalturaLanguage('English (American)');
	static eo = new KalturaLanguage('Esperanto');
	static es = new KalturaLanguage('Spanish');
	static et = new KalturaLanguage('Estonian');
	static eu = new KalturaLanguage('Basque');
	static fa = new KalturaLanguage('Farsi');
	static fi = new KalturaLanguage('Finnish');
	static fj = new KalturaLanguage('Fiji');
	static fo = new KalturaLanguage('Faeroese');
	static fr = new KalturaLanguage('French');
	static fy = new KalturaLanguage('Frisian');
	static ga = new KalturaLanguage('Irish');
	static gd = new KalturaLanguage('Gaelic (Scottish)');
	static gl = new KalturaLanguage('Galician');
	static gn = new KalturaLanguage('Guarani');
	static gu = new KalturaLanguage('Gujarati');
	static gv = new KalturaLanguage('Gaelic (Manx)');
	static ha = new KalturaLanguage('Hausa');
	static he = new KalturaLanguage('Hebrew');
	static hi = new KalturaLanguage('Hindi');
	static hr = new KalturaLanguage('Croatian');
	static hu = new KalturaLanguage('Hungarian');
	static hy = new KalturaLanguage('Armenian');
	static ia = new KalturaLanguage('Interlingua');
	static id = new KalturaLanguage('Indonesian');
	static ie = new KalturaLanguage('Interlingue');
	static ik = new KalturaLanguage('Inupiak');
	static in = new KalturaLanguage('Indonesian');
	static is = new KalturaLanguage('Icelandic');
	static it = new KalturaLanguage('Italian');
	static iu = new KalturaLanguage('Inuktitut');
	static iw = new KalturaLanguage('Hebrew');
	static ja = new KalturaLanguage('Japanese');
	static ji = new KalturaLanguage('Yiddish');
	static jv = new KalturaLanguage('Javanese');
	static ka = new KalturaLanguage('Georgian');
	static kk = new KalturaLanguage('Kazakh');
	static kl = new KalturaLanguage('Greenlandic');
	static km = new KalturaLanguage('Cambodian');
	static kn = new KalturaLanguage('Kannada');
	static ko = new KalturaLanguage('Korean');
	static ks = new KalturaLanguage('Kashmiri');
	static ku = new KalturaLanguage('Kurdish');
	static ky = new KalturaLanguage('Kirghiz');
	static la = new KalturaLanguage('Latin');
	static li = new KalturaLanguage('Limburgish ( Limburger)');
	static ln = new KalturaLanguage('Lingala');
	static lo = new KalturaLanguage('Laothian');
	static lt = new KalturaLanguage('Lithuanian');
	static lv = new KalturaLanguage('Latvian (Lettish)');
	static mg = new KalturaLanguage('Malagasy');
	static mi = new KalturaLanguage('Maori');
	static mk = new KalturaLanguage('Macedonian');
	static ml = new KalturaLanguage('Malayalam');
	static mn = new KalturaLanguage('Mongolian');
	static mo = new KalturaLanguage('Moldavian');
	static mr = new KalturaLanguage('Marathi');
	static ms = new KalturaLanguage('Malay');
	static mt = new KalturaLanguage('Maltese');
	static mu = new KalturaLanguage('Multilingual');
	static my = new KalturaLanguage('Burmese');
	static na = new KalturaLanguage('Nauru');
	static ne = new KalturaLanguage('Nepali');
	static nl = new KalturaLanguage('Dutch');
	static no = new KalturaLanguage('Norwegian');
	static oc = new KalturaLanguage('Occitan');
	static om = new KalturaLanguage('Oromo (Afan, Galla)');
	static or = new KalturaLanguage('Oriya');
	static pa = new KalturaLanguage('Punjabi');
	static pl = new KalturaLanguage('Polish');
	static ps = new KalturaLanguage('Pashto (Pushto)');
	static pt = new KalturaLanguage('Portuguese');
	static qu = new KalturaLanguage('Quechua');
	static rm = new KalturaLanguage('Rhaeto-Romance');
	static rn = new KalturaLanguage('Kirundi (Rundi)');
	static ro = new KalturaLanguage('Romanian');
	static ru = new KalturaLanguage('Russian');
	static rw = new KalturaLanguage('Kinyarwanda (Ruanda)');
	static sa = new KalturaLanguage('Sanskrit');
	static sd = new KalturaLanguage('Sindhi');
	static sg = new KalturaLanguage('Sangro');
	static sh = new KalturaLanguage('Serbo-Croatian');
	static si = new KalturaLanguage('Sinhalese');
	static sk = new KalturaLanguage('Slovak');
	static sl = new KalturaLanguage('Slovenian');
	static sm = new KalturaLanguage('Samoan');
	static sn = new KalturaLanguage('Shona');
	static so = new KalturaLanguage('Somali');
	static sq = new KalturaLanguage('Albanian');
	static sr = new KalturaLanguage('Serbian');
	static ss = new KalturaLanguage('Siswati');
	static st = new KalturaLanguage('Sesotho');
	static su = new KalturaLanguage('Sundanese');
	static sv = new KalturaLanguage('Swedish');
	static sw = new KalturaLanguage('Swahili (Kiswahili)');
	static ta = new KalturaLanguage('Tamil');
	static te = new KalturaLanguage('Telugu');
	static tg = new KalturaLanguage('Tajik');
	static th = new KalturaLanguage('Thai');
	static ti = new KalturaLanguage('Tigrinya');
	static tk = new KalturaLanguage('Turkmen');
	static tl = new KalturaLanguage('Tagalog');
	static tn = new KalturaLanguage('Setswana');
	static to = new KalturaLanguage('Tonga');
	static tr = new KalturaLanguage('Turkish');
	static ts = new KalturaLanguage('Tsonga');
	static tt = new KalturaLanguage('Tatar');
	static tw = new KalturaLanguage('Twi');
	static ug = new KalturaLanguage('Uighur');
	static uk = new KalturaLanguage('Ukrainian');
	static un = new KalturaLanguage('Undefined');
	static ur = new KalturaLanguage('Urdu');
	static uz = new KalturaLanguage('Uzbek');
	static vi = new KalturaLanguage('Vietnamese');
	static vo = new KalturaLanguage('Volapuk');
	static wo = new KalturaLanguage('Wolof');
	static xh = new KalturaLanguage('Xhosa');
	static yi = new KalturaLanguage('Yiddish');
	static yo = new KalturaLanguage('Yoruba');
	static zh = new KalturaLanguage('Chinese');
	static zu = new KalturaLanguage('Zulu');
}
KalturaTypesFactory.registerType('KalturaLanguage',KalturaLanguage);